version: '3'

services:
        db:
                image: postgres
                environment:
                        - POSTGRES_DB=futsaldb
                        - POSTGRES_USER=ricardinho
                        - POSTGRES_PASSWORD=ramin365
                        - POSTGRES_HOST_AUTH_METHOD=trust
                networks:
                        - db_network
                volumes:
                        - db_volume:/var/lib/postgresql/data

        futsal:
                build: .
                command: gunicorn store.wsgi:application --bind 0.0.0.0:8000
                volumes:
                        - .:/code
                ports:
                        - 8000:8000
                networks:
                        - db_network
                depends_on:
                        - db


networks:
        db_network:
                driver: bridge
volumes:
        db_volume:

