# Generated by Django 4.1.3 on 2022-12-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.ManyToManyField(related_name='variations', to='shop.size'),
        ),
    ]
