# Generated by Django 4.1.3 on 2022-12-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_size_variation_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('alborz', 'Alborz'), ('ardabil', 'Ardabil'), ('east azerbaijan', 'East Azerbaijan'), ('west azerbaijan', 'West Azerbaijan'), ('bushehr', 'Bushehr'), ('chahar mahaal and bakhtiari', 'Chahar Mahaal and Bakhtiari'), ('fars', 'Fars'), ('gilan', 'Gilan'), ('golestan', 'Golestan'), ('hamadan', 'Hamadan'), ('hormozgan', 'Hormozgan'), ('ilam', 'Ilam'), ('isfahan', 'Isfahan'), ('kerman', 'Kerman'), ('kermanshah', 'Kermanshah'), ('north khorasan', 'North Khorasan'), ('razavi khorasan', 'Razavi Khorasan'), ('south khorasan', 'South Khorasan'), ('khuzestan', 'Khuzestan'), ('kohgiluyeh and boyer ahmad', 'Kohgiluyeh and Boyer Ahmad'), ('kurdistan', 'Kurdistan'), ('lorestan', 'Lorestan'), ('markazi', 'Markazi'), ('mazandaran', 'Mazandaran'), ('qazvin', 'Qazvin'), ('qom', 'Qom'), ('semnan', 'Semnan'), ('sistan and baltchestan', 'Sistan and Baluchestan'), ('tehran', 'Tehran'), ('yazd', 'Yazd'), ('zanjan', 'Zanjan')], default='tehran', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shop.province'),
        ),
    ]
