# Generated by Django 4.1.3 on 2022-11-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_slug_category',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_slug_category'),
        ),
    ]
