# Generated by Django 4.1.3 on 2022-11-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_category_unique_slug_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.CharField(choices=[('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=2),
        ),
    ]
